version: apps/v1
kind: Deployment
metadata:
    name: erp-bd-deployment
    labels:
      app: erp
spec:
  replicas: 2
  selector:
    matchLabels: 
      app: erp    
  
  template:
    metadata:
      labels:
        app: erp
    spec:
      containers:
      - name: erp-bd
        image: postgres:alpine3.19
        ports: 
        - containerPort: 5432
      resources:
        requests:
          cpu: "10m"
          memory: "100mi"
        limits:
        - cpu: "100m"
        - memory: "500mi"
      