version: "3"

networks:
  gitea:
    external: false
services:
  server:
    image: postgres:alpine3.19
    container_name: postgress
    environment:
      - POSTGRES_PASSWORD=postgress
      - POSTGRES_USER=postgress
      - POSTGRES_DB=postgress
      - PGDATA=./mysql:/var/lib/postgresql/data
    restart: always
    volumes:
      - ./mysql:/var/lib/postgresql/data
    ports:
      - "5432:5432"